// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6mj8n-TzSgmClDxjj2RT9rYBHiNLudO0',
    appId: '1:510377352156:web:732acf3ce4108b335d8d19',
    messagingSenderId: '510377352156',
    projectId: 'chat-app-7438b',
    authDomain: 'chat-app-7438b.firebaseapp.com',
    storageBucket: 'chat-app-7438b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJdXjCBY9Aocu3JZpED-OzYpvG9rW-hg',
    appId: '1:510377352156:android:2c177299740b20a65d8d19',
    messagingSenderId: '510377352156',
    projectId: 'chat-app-7438b',
    storageBucket: 'chat-app-7438b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaQnZBMyAQ_Xn1GK6qIkyijIBZQ881D_U',
    appId: '1:510377352156:ios:c0ab5ef39f0ef3a65d8d19',
    messagingSenderId: '510377352156',
    projectId: 'chat-app-7438b',
    storageBucket: 'chat-app-7438b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaQnZBMyAQ_Xn1GK6qIkyijIBZQ881D_U',
    appId: '1:510377352156:ios:c0ab5ef39f0ef3a65d8d19',
    messagingSenderId: '510377352156',
    projectId: 'chat-app-7438b',
    storageBucket: 'chat-app-7438b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6mj8n-TzSgmClDxjj2RT9rYBHiNLudO0',
    appId: '1:510377352156:web:af148951bdb026e65d8d19',
    messagingSenderId: '510377352156',
    projectId: 'chat-app-7438b',
    authDomain: 'chat-app-7438b.firebaseapp.com',
    storageBucket: 'chat-app-7438b.appspot.com',
  );
}
